apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b56w1voxh-dotnet-basic
  janus-idp.io/tekton: b56w1voxh-dotnet-basic
  backstage.io/kubernetes-id: b56w1voxh-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b56w1voxh-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
